### ISSUE TITLE
Unable to install grpcio on Python 3.9 on macOS Big Sur

### ISSUE THREAD

**Issue by chmod77** [chmod77/dfuse-python#8]
Installing grpcio on Mac OS Big Sur fails with compile errors. This seems to be related to https://github.com/grpc/grpc/issues/24344#issuecomment-733662710 

Watching for updates on the same, and will update as soon as it is resolved on the grpcio side

**Comment by max-sixty** [comment]
Is this issue specific to Python 3.9 on Big Sur? I'm struggling to install on Python 3.8 too, I think because of the packaging issues on the linked comment.

**Comment by chmod77** [comment]
Looks like it is specific to 3.9, as I was able to install it on 3.8 on Big Sur

**Comment by chmod77** [comment]
This has been resolved from the `grpcio` stream. https://pypi.org/project/grpcio-tools/1.34.0/#files.

Closing this issue now.
